FischPark/FischPark/Controllers/PokedexController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using PokeAPI;
using FischPark.Models;
using System.Threading.Tasks;
using System.Globalization;

namespace FischPark.Controllers
{
    public class PokedexController : Controller
    {
        static string ConnectionString = ConfigurationManager.ConnectionStrings["FischParkConnectionString"].ConnectionString;
        IDbConnection conn = new SqlConnection(ConnectionString);
        
        public async Task<ActionResult> Index()
        {
            List<PokedexModel> pokedex;

            pokedex = conn.Query<PokedexModel>("pkmn.Pokedex_List", commandType: CommandType.StoredProcedure).ToList();
            PokedexViewModel viewModel = new PokedexViewModel(pokedex);

            foreach (var pokemon in viewModel.pokedex)
            {
                PokemonSpecies p = await DataFetcher.GetApiObject<PokemonSpecies>(pokemon.Pokedex_ID.Value);
                pokemon.Name = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(p.Name);
            }

            foreach (var pokemon in viewModel.pokedex)
            {
                if (pokemon.Percentage == "0")
                {
                    pokemon.BackgroundColor = "#FFFFFF";
                }
                else if (pokemon.Percentage == "25")
                {
                    pokemon.BackgroundColor = "#C1C7F9";
                }
                else if (pokemon.Percentage == "50")
                {
                    pokemon.BackgroundColor = "#979EEE";
                }
                else if (pokemon.Percentage == "75")
                {
                    pokemon.BackgroundColor = "#6871D5";
                }
                else if (pokemon.Percentage == "100")
                {
                    pokemon.BackgroundColor = "#384498";
                }
            }

                return View(viewModel);
        }

        public ActionResult UpdateIndex()
        {
            return View();
        }

        public ActionResult UpdateGetID(PokedexModel model)
        {
            return PartialView("_UpdateGetID", model);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateGet(PokedexModel model)
        {
            if (model.Pokedex_ID > 0)
            {
                DynamicParameters p = new DynamicParameters();
                p.Add("@Pokedex_ID", model.Pokedex_ID.Value, DbType.Int32);

                model = conn.Query<PokedexModel>("pkmn.Pokedex_Get", param: p, commandType: CommandType.StoredProcedure).FirstOrDefault();

                PokemonSpecies pkmn = await DataFetcher.GetApiObject<PokemonSpecies>(model.Pokedex_ID.Value);
                model.Name = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(pkmn.Name);
            }
            
            return PartialView("_UpdateForm", model);
        }

        [HttpPost]
        public ActionResult UpdateFinal(PokedexModel model)
        {
            if (model.Pokedex_ID > 0)
            {
                DynamicParameters p = new DynamicParameters();
                p.Add("@Pokedex_ID", model.Pokedex_ID.Value, DbType.Int32);
                p.Add("@Male", model.Male, DbType.String);
                p.Add("@Female", model.Female, DbType.String);
                p.Add("@Shiny", model.Shiny, DbType.String);
                p.Add("@Lucky", model.Lucky, DbType.String);

                model = conn.Query<PokedexModel>("pkmn.Pokedex_Update", param: p, commandType: CommandType.StoredProcedure).FirstOrDefault();
            }

            ModelState.Clear();

            return PartialView("_UpdateGetID", model);
        }


        public async Task<string> GetPokemonName(int pokedex_ID)
        {
            PokemonSpecies p = await DataFetcher.GetApiObject<PokemonSpecies>(pokedex_ID);
            string Return = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(p.Name);

            return Return;
        }
    }
}

FischPark/FischPark/Views/Pokedex/Index.cshtml
@model FischPark.Models.PokedexViewModel

@{
    ViewBag.Title = "BugGirlKeiki's Pokedex";
}

<style type="text/css">
    table.table tr td {
        vertical-align: middle
    }

    .Male-Yes {
        background-color: navy;
        color: white;
        width: 50px;
    }

    .Male-No {
        background-color: white;
        color: navy;
        width: 50px;
    }

    .Male-NA {
        background-color: black;
        color: black;
        width: 50px;
    }

    .Female-Yes {
        background-color: crimson;
        color: white;
        width: 50px;
    }

    .Female-No {
        background-color: white;
        color: crimson;
        width: 50px;
    }

    .Female-NA {
        background-color: black;
        color: black;
        width: 50px;
    }

    .Shiny-Yes {
        background-color: gold;
        color: white;
        width: 50px;
    }

    .Shiny-No {
        background-color: white;
        color: gold;
        width: 50px;
    }

    .Lucky-Yes {
        background-color: green;
        color: white;
        width: 50px;
    }

    .Lucky-No {
        background-color: white;
        color: green;
        width: 50px;
    }
</style>

<h1>BugGirlKeiki's Pokedex</h1>

@foreach (var pokemon in Model.pokedex)
{
    <div class="col-md-2">
        <table class="text-center" width="140" style="border:1px solid #384498;margin-bottom:15px;color:white;background-color:@pokemon.BackgroundColor">

            @*<tr><td colspan="4"><img src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/@(pokemon.Pokedex_ID).png" width="40" height="40" /></td></tr>*@
            <tr><td colspan="4" style="padding-top:10px;"><img src="https://img.pokemondb.net/sprites/ruby-sapphire/normal/@(pokemon.Name.ToLower()).png" width="50" height="50" /></td></tr>
            <tr><td colspan="4">@pokemon.Name</td></tr>
            <tr>
                <td class="Male-@pokemon.Male">M</td>
                <td class="Female-@pokemon.Female">F</td>
                <td class="Shiny-@pokemon.Shiny">S</td>
                <td class="Lucky-@pokemon.Lucky">L</td>
            </tr>
            @*<tr><td colspan="4">&nbsp;</td></tr>*@
        </table>
    </div>
}

<div class="row col-md-12">&nbsp;</div>

FischPark/FischPark/Views/Pokedex/UpdateIndex.cshtml
@model FischPark.Models.PokedexModel

@{
    ViewBag.Title = "BugGirlKeiki's Pokedex SECRET UPDATER";
}

<h1>Update Pokedex</h1>

<div id="PokedexUpdaterMain" class="container">

@Html.Action("UpdateGetID", Model)

</div>

<script>

    function submitForm() {
        $('#Pokedex_ID').blur(function () {
            $(this).closest('form').submit();
        });
    }

    $(document).ready(function () {
        submitForm();
    });

    
</script>

FischPark/FischPark/Views/Pokedex/_UpdateForm.cshtml
@model FischPark.Models.PokedexModel



@using (Ajax.BeginForm("UpdateFinal", "Pokedex",
        new AjaxOptions
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "PokedexUpdaterMain",
            OnSuccess = "submitForm(); $('#Pokedex_ID').focus(); $('#Pokedex_ID').val('');"
        }))
{



<div class="form-horizontal">
    <div class="form-group" style="font-weight:bold;">
        <div class="control-label col-xs-2">@Html.DisplayFor(x => x.Name)</div>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(model => model.Male, htmlAttributes: new { @class = "control-label col-xs-2" })
        @Html.EditorFor(x => x.Male, new { htmlAttributes = new { @class = "form-control col-xs-3" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Female, htmlAttributes: new { @class = "control-label col-xs-2" })
        @Html.EditorFor(x => x.Female, new { htmlAttributes = new { @class = "form-control col-xs-3" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Shiny, htmlAttributes: new { @class = "control-label col-xs-2" })
        @Html.EditorFor(x => x.Shiny, new { htmlAttributes = new { @class = "form-control col-xs-3" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Lucky, htmlAttributes: new { @class = "control-label col-xs-2" })
        @Html.EditorFor(x => x.Lucky, new { htmlAttributes = new { @class = "form-control col-xs-3" } })
    </div>

    <div class="form-group">
        @Html.HiddenFor(x => x.Pokedex_ID)
        <div class="col-xs-2"></div>
        <input type="submit" value="Update" class="btn btn-primary col-xs-3" />
    </div>

</div>

}

FischPark/FischPark/Views/Pokedex/_UpdateGetID.cshtml
@model FischPark.Models.PokedexModel

<div id="PokedexUpdaterID" class="row">
    @using (Ajax.BeginForm("UpdateGet", "Pokedex",
    new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "PokedexUpdaterForm",
        OnSuccess = "$('#Male').focus();"
    }))
    {
    <div class="form-horizontal">
        <div class="form-group">
        @Html.LabelFor(model => model.Pokedex_ID, htmlAttributes: new { @class = "control-label col-xs-2" })
        @Html.EditorFor(x => x.Pokedex_ID, new { htmlAttributes = new { @class = "form-control col-xs-3" } })
        <input type="submit" class="col-xs-1" value="OK" hidden/>
    </div>
    </div>
    }
</div>


<div id="PokedexUpdaterForm" class="row"></div>