FischPark/FischPark/Controllers/PkmnBiomesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using FischPark.Models;

namespace FischPark.Controllers
{
    public class PkmnBiomesController : Controller
    {

        public ActionResult Index()
        {
            string ConnectionString = ConfigurationManager.ConnectionStrings["FischParkConnectionString"].ConnectionString;
            IDbConnection conn = new SqlConnection(ConnectionString);

            List<PkmnBiomesModel> castResults;

            castResults = conn.Query<PkmnBiomesModel>("pkmn.Biomes_List", commandType: CommandType.StoredProcedure).ToList();

            PkmnBiomesViewModel viewModel = new PkmnBiomesViewModel(castResults);

            return View(viewModel);
        }
    }
}

FischPark/FischPark/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Biomes", "Index", "PkmnBiomes")</li>
                    <li>@Html.ActionLink("Pokedex", "Index", "Pokedex")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/unobtrusive")
    @RenderSection("scripts", required: false)
</body>
</html>